export const ActionTypes = {
  FETCH_DATA: 'FETCH_DATA',
  LOCATION_ERROR: 'LOCATION_ERROR',
  CITY_NAME_ERROR: 'CITY_NAME_ERROR',
  DISPLAY_DATA: 'DISPLAY_DATA',
  SHOW_ALERT_POPUP: 'SHOW_ALERT_POPUP',
  SHOW_DAILY_DETAILS: 'SHOW_DAILY_DETAILS',
  CHOSEN_DAY: 'CHOSEN_DAY',
  LOADING: 'LOADING',
  CELSIUS_TEMP: 'CELSIUS_TEMP',
} as const;
